apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitrot-backend
  labels:
    app: gitrot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitrot-backend
  template:
    metadata:
      labels:
        app: gitrot-backend
    spec:
      containers:
        - name: backend
          image: mcaupybugs/gitrot-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: ENVIRONMENT
              value: "production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
