apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitrot-ingress
  namespace: gitrot
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - gitrot.mcaupybugs.com # Replace with your actual domain
      secretName: gitrot-tls
  rules:
    - host: gitrot.mcaupybugs.com # Replace with your actual domain
      http:
        paths:
          # Backend API routes - rewrite /api/foo to /foo
          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gitrot-backend-service
                port:
                  number: 8000
          # Frontend routes (everything else including static files)
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: gitrot-frontend-service
                port:
                  number: 3000
