apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gitrot-keyvault-secrets
  namespace: gitrot
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "5a2f33f4-e2e8-4ca6-8a2d-33862dfe9e8d"
    keyvaultName: "mcaupybugs-keyvault"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: AZURE-OPENAI-API-KEY
          objectType: secret
        - |
          objectName: GEMINI-API-KEY
          objectType: secret
    tenantId: "2f68c1da-e933-4e92-938c-7e7d099b43aa"
  secretObjects:
    - secretName: gitrot-app-secrets
      type: Opaque
      data:
        - objectName: AZURE-OPENAI-API-KEY
          key: AZURE_OPENAI_API_KEY
        - objectName: GEMINI-API-KEY
          key: GEMINI_API_KEY
