name: Deploy to Docker Hub

on:
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gitrot-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gitrot-backend:latest

      - name: Build and push frontend
        run: |
          cd gitrot-frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gitrot-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gitrot-frontend:latest

      - name: Summary
        run: |
          echo "✅ Images pushed to Docker Hub:"
          echo "- ${{ secrets.DOCKERHUB_USERNAME }}/gitrot-backend:latest"
          echo "- ${{ secrets.DOCKERHUB_USERNAME }}/gitrot-frontend:latest"
